### ISSUE TITLE
run jgi_summarize_bam_contig_depths error

### ISSUE THREAD

**Issue by JLUVicent** [dyxstat/HiCBin#3]
when I run `./jgi_summarize_bam_contig_depths --outputDepth coverage410.txt --pairedContigs pair410.txt test/sorted.bam`,I 		get an error  `Please execute 'samtools sort' on unsorted input bam files and try again!` . But I have run the command `samtools sort -o sorted.bam -n align_test.bam `, I still make the mistake. I don't know what to do. I would appreciate it if you could give me some advice. Thank you!

**Comment by dyxstat** [comment]
Hi,

Can you try 'samtools sort align_test.bam -o sorted.bam' since '-n' option is used to sort bam file by the read name?

Best,
Yancey

**Comment by JLUVicent** [comment]
Thank you very much for your answer. I have solved my problem !
