### ISSUE TITLE
question about how to get the tax_file?

### ISSUE THREAD

**Issue by JLUVicent** [dyxstat/HiCBin#5]
Dear sir,
I am using HiCBin to process my data, I want to use the TAXAassign to get the labels,but I get the following error after install the TAXAassign.
![image](https://user-images.githubusercontent.com/55722910/201448155-fa936b68-bba4-42a1-9aab-05429b3ce972.png)
The follow is my software version:
```
python=2.7.18
blast=2.13.0
mysql=5.7.40
perl=5.26.1
```
Although at the beginning I ran the program and reported the following error due to perl version problem:
```
. Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/jianchang/software/TAXAassign/scripts/blast_gen_assignments.pl line 108
```
But I have modified the blast_gen_assignments.pl file to fit this version
Can you give me some advice? Thank you!

**Comment by dyxstat** [comment]
Sorry, Vicent. I am struggling to understand your errors since I never run into such trouble before. I am afraid that I cannot give you some good advice at the current stage. You can check whether your testBF.out file is empty. If not, most steps of TAXAassign could be executed normally other than the last step of running python script blast_concat_taxcon.py to aggregate the taxonomy assignment results.

Hope the above can help you to some extent.
Yancey

**Comment by JLUVicent** [comment]
Thank you for your reply, my test_BF.out file is not empty, it is as follows.
![image](https://user-images.githubusercontent.com/55722910/201875254-29f65131-0a55-4e32-a9e7-b621b609fbdb.png)
the error is following:
![image](https://user-images.githubusercontent.com/55722910/201875472-daf226ef-3980-473d-ba13-e93c2f7cdf4a.png)
The line that went wrong in the. / TAXAassign.sh file is line348, where it reads each line of test_BF.out as a file path, the following is the error line:
![image](https://user-images.githubusercontent.com/55722910/201876683-e9ae8b8b-10c9-4f92-97b1-ab42e9c664bc.png)
I've been confused for days. Can you give me some advice?

**Comment by dyxstat** [comment]
Hi Vicent,

Sorry for the late reply. I think this line is activated when you use parallel computing. 

I am sorry I cannot provide you with useful advice to solve your problem. I can only tell you the transformation from '*_BF.out' to '*_BFT.out' is the last step, which should be accomplished by the script 'blast_concat_taxon.py'.

Best,
Yancey
