### ISSUE TITLE
TypeError during "Generating contig labels..."

### ISSUE THREAD

**Issue by cyanoluu** [dyxstat/HiCBin#6]
Hi,

I would like to ask you for a help with this error. All files were prepared as you recommended in documentation. Only one difference is that my bam file is merged file of two bam files and coverage was calculate from the merged file.  

INFO     | 2023-03-16 19:53:23,043 | contact_matrix | Reading fasta file...
Analyzing contigs in reference fasta: 100%|██████████████████████████████████████████████████████████████| 59145/59145 [00:13<00:00, 4464.22it/s]
INFO     | 2023-03-16 19:53:44,824 | contact_matrix | Generating contig labels...
Traceback (most recent call last):
  File "./hicbin.py", line 196, in <module>
    min_signal=ifelse(args.min_signal, runtime_defaults['min_signal']))
  File "/home/sehnal/HiCBin/contact_matrix.py", line 591, in __init__
    self._generate_tax()
  File "/home/sehnal/HiCBin/contact_matrix.py", line 715, in _generate_tax
    taxlist = taxaassignMat[: , 1:].sum(1)  #taxassign name
  File "/home/sehnal/miniconda3/envs/HiCBin_env/lib/python3.7/site-packages/numpy/core/_methods.py", line 47, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
TypeError: can only concatenate str (not "float") to str

Thanks for reply,
Ludek

**Comment by dyxstat** [comment]
Thanks for trying our software! Could you provide me with your log file?

Best

**Comment by cyanoluu** [comment]
Thanks for reply. Here is copy from my log.

DEBUG    | 2023-03-16 19:53:23,043 |    main | HiCBin v1.0.0, released at 01/2021
DEBUG    | 2023-03-16 19:53:23,043 |    main | 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)  [GCC 9.3.0]
DEBUG    | 2023-03-16 19:53:23,043 |    main | Command line: ./hicbin.py pipeline --min-binsize 250000 ./met20.fasta ./met20_merged.bam ./met20_Taxonomy.csv ./cover.txt ./hic_bins
INFO     | 2023-03-16 19:53:23,043 | contact_matrix | Reading fasta file...
DEBUG    | 2023-03-16 19:53:44,744 | contact_matrix | There are 59145 contigs in reference fasta
INFO     | 2023-03-16 19:53:44,824 | contact_matrix | Generating contig labels...

**Comment by dyxstat** [comment]
Hi,

This bug occurs due to your input  ./met20_Taxonomy.csv file. Can you provide me with several rows of this file since it seems that all your data in this file are numbers, not the taxonomic names?

Best

**Comment by cyanoluu** [comment]
Hi,

below are two example rows from taxonomy.csv file. Thank you very much for your help!

contig_22266_polypolish	F	NCBI | cellular organisms | Bacteria | Proteobacteria | delta/epsilon subdivisions | Deltaproteobacteria | Myxococcales | Cystobacterineae | Archangiaceae
-- | -- | -- | -- | -- | -- | -- | -- | --
contig_38995_polypolish	G	NCBI | cellular organisms | Bacteria | Proteobacteria | delta/epsilon subdivisions | Deltaproteobacteria | Myxococcales | Cystobacterineae | Archangiaceae | Archangium

And important point, I used MEGAN for taxonomy.

Best

**Comment by dyxstat** [comment]
Hi,

I'm sorry for not getting back to you sooner. I have tried these two rows and succeeded in inputting them into HiCBin.
However, the example rows are not desired for HiCBin. Please refer to https://github.com/dyxstat/HiCBin/issues/4 if you cannot use TAXAassign to generate a taxonomy file. Sorry for the inconvenience.

Best
