### ISSUE TITLE
coverage file index error

### ISSUE THREAD

**Issue by glefhoho** [dyxstat/HiCBin#8]
Hi, hope you are well. I met this below error. Any ideas? Thanks in advance.

File "/home/HiCBin/contact_matrix.py", line 584, in __init__
    cov = cov.values[0: , [0,2]]
IndexError: index 2 is out of bounds for axis 1 with size

**Comment by dyxstat** [comment]
Hi,

Thanks for using our software! Could you please provide your coverage file?

BTW, we have designed a new Hi-C-based binning method [MetaCC](https://github.com/dyxstat/MetaCC), which has been accepted by Nature Communications and will be out soon. It is much easier to use and achieves much better performance. Welcome to try it!

Best,
Yuxuan

**Comment by glefhoho** [comment]
Hi Yuxuan, 
Thanks for your reply! The example coverage.txt I used is below. I actually tried both cov. percentage and real cov. values (by bbtools). I am speculating that I kinda messup something but also getting close to run the codes.

BTW, big congrats to the MetaCC. I will try it for sure.

#ID coverage_percent
k141_46344 0.434534
k141_220134 0.774325
k141_602440 0.190309
k141_0 5.0929
k141_312815 0.184243
k141_278060 0.128474
k141_34758 0.229796
k141_822555 0.133345
k141_683535 0.28941
k141_127446 0.172794
k141_254890 0.188089
k141_220135 0.289701
k141_231721 0.165581
k141_695120 0.177263
k141_104274 0.296794
k141_521346 0.487207
k141_440250 0.219653

**Comment by dyxstat** [comment]
Thanks a lot!

By default, we assume that the contig name is in the first column and the coverage information is in the third column (this is the format generated by MetaBAT2). I think you can slightly modify your coverage file to solve this problem., for example, duplicate the second column.

Yuxuan
